[package]
name = "casper-delta-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-delta-contracts = { path = "../casper-delta-contracts" }
casper_trade_contracts = { path = "../../casper-trade/casper_trade_contracts" }
styks-contracts = { workspace = true }
odra = { workspace = true }
odra-cli = { workspace = true }
ureq = "3.0.12"
serde_json = "1.0.140"
dotenv = "0.15"
chrono = "0.4"

[dev-dependencies]
odra-test = { workspace = true }
mockall = "0.14.0"

[patch.crates-io]
odra = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-cli = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-core = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-modules = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-test = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-wasm-client = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }
odra-wasm-client-builder = { git = "https://github.com/odradev/odra.git", branch = "feature/mut-no-return" }

[[bin]]
name = "casper-delta-cli"
path = "src/cli.rs"
