[package]
name = "casper-delta-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-delta-contracts = { path = "../casper-delta-contracts" }
casper_trade_contracts = { path = "../../casper-trade/casper_trade_contracts" }
styks-contracts = { workspace = true }
odra = { workspace = true }
odra-cli = { workspace = true }
ureq = "3.0.12"
serde_json = "1.0.140"
dotenv = "0.15"
chrono = "0.4"

[dev-dependencies]
odra-test = { workspace = true }
mockall = "0.14.0"

[[bin]]
name = "casper-delta-cli"
path = "src/cli.rs"
